### ISSUE TITLE
The one and only example showing how to use ion-js is broken.

### ISSUE THREAD

**Issue by derv82** [amzn/ion-js#79]
From the main page at https://github.com/amzn/ion-js

```javascript
var ionJs = require("ion-js")

var ionData = "{ hello: \"Ion\" }"; 
var ionReader = ionJs.makeReader(ionData); 
ionReader.next(); 
ionReader.stepIn(); 
ionReader.next(); 
var hello = ionReader.fieldName(); 
var ion = ionReader.stringValue(); 
ionReader.stepOut(); 
console.log(ion.concat(", ").concat(hello));
```

This is the output:

```javascript
"ello: \"Ion, hello"
```

Pretty sure the output is supposed to be `"Ion, hello"`

Tested using:

1. https://amzn.github.io/ion-js/browser/scripts/ion-bundle.min.js (recommended on the README)
2. https://npm.runkit.com/ion-js ("Try it yourself" on the README)

Looks like parsing of strings inside of structs is broken:

```javascript
var ionJs = require("ion-js");
var r = ionJs.makeReader('{key:"value"}');
r.next(); r.stepIn(); r.next();
console.log("fieldName: " + r.fieldName());
console.log("stringValue: " + r.stringValue());

// output:
"fieldName: key"
"stringValue: ey:\"value"
```

**Comment by wesboyt** [comment]
After some deep diving this issue stems from underneath the hood of the type interpreting logic within the text parser. Will update when resolved.

**Comment by wesboyt** [comment]
This commit caused the issue: 8a39caf8f51697447d8a9dee38681664db217dcf
We'll start looking into it there.

**Comment by wesboyt** [comment]
This has bee fixed on the recent PR to development: #118 
Thank you for participating with us on IonJS!

**Comment by anandharshan** [comment]
Could you please merge it into public

**Comment by wesboyt** [comment]
Hey anand, what do you mean public? I believe this fix is available on Npm and Github. Is there another repo you are referring to?

**Comment by chenliu0831** [comment]
I think it's still broken in the https://npm.runkit.com/ion-js, which is referenced in the homepage

**Comment by wesboyt** [comment]
I spoke to the runkit team and as the current release has a beta flag it is not shown on the runkit link.
The fixes are available in the library here and on NPM, feel free to use the text side of the library.
